// COPYRIGHT Dassault Systemes 2018
//===================================================================
//
// CreateLineDlg.h
// The dialog : CreateLineDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   DIALOG
//End CAA2 Wizard Generation Report
//
//  Nov 2018  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#ifndef CreateLineDlg_H
#define CreateLineDlg_H

#include "CATDlgDialog.h"
#include "CATDlgInclude.h"

//----------------------------------------------------------------------

/**
 * Describe the purpose of your panel here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog framework.
 * (consult base class description).
 */
class CreateLineDlg: public CATDlgDialog
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( CreateLineDlg, CATDlgDialog )

  public:

  CreateLineDlg();
  virtual ~CreateLineDlg();

  void Build ();
  CATDlgSelectorList *GetCATDlgSelectorListFirstPoint();
  CATDlgSelectorList *GetCATDlgSelectorListSecondPoint();
  protected:

  private:


//CAA2 WIZARD WIDGET DECLARATION SECTION
 CATDlgLabel*      _LabelFirstPoint;
 CATDlgLabel*      _LabelSecondPoint;
 CATDlgSelectorList*      _SelectorListFirstPoint;
 CATDlgSelectorList*      _SelectorListSecondPoint;
//END CAA2 WIZARD WIDGET DECLARATION SECTION
};

//----------------------------------------------------------------------

#endif
