// COPYRIGHT Dassault Systemes 2017
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework FMPublic
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  Oct 2017  Creation: Code generated by the CAA wizard  Monkey.D.Luff
//===================================================================
// DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
AddPrereqComponent ("System", Public);
// END WIZARD EDITION ZONE
