// COPYRIGHT Dassault Systemes 2019
//===================================================================
//
// TestDlg.cpp
// The dialog : TestDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Jan 2019  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#include "TestDlg.h"
#include "CATApplicationFrame.h"
#include "CATDlgGridConstraints.h"
#include "CATMsgCatalog.h"
#ifdef TestDlg_ParameterEditorInclude
#include "CATIParameterEditorFactory.h"
#include "CATIParameterEditor.h"
#include "CATICkeParm.h"
#endif




//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
TestDlg::TestDlg() :
  CATDlgDialog ((CATApplicationFrame::GetApplicationFrame())->GetMainWindow(),
//CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
"TestDlg",CATDlgGridLayout
//END CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
                               )
{
//CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
 _LabelLine = NULL;
 _Container002 = NULL;
 _SelectorListLine = NULL;
 _Container003 = NULL;
 _PushButtonCOUT = NULL;
 _Container004 = NULL;
 _LabelAxis = NULL;
 _SelectorListFace = NULL;
 _PushButtonMidPtOnSurf = NULL;
 _PushButtonProjection = NULL;
 _PushButtonStartOtherCmd = NULL;
 _PushButtonCompass = NULL;
 _PushButtonReadTxt = NULL;
 _PushButton3DView = NULL;
//END CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
TestDlg::~TestDlg()
{
//  Do not delete the control elements of your dialog: 
//     this is done automatically
//  --------------------------------------------------
//CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
 _LabelLine = NULL;
 _Container002 = NULL;
 _SelectorListLine = NULL;
 _Container003 = NULL;
 _PushButtonCOUT = NULL;
 _Container004 = NULL;
 _LabelAxis = NULL;
 _SelectorListFace = NULL;
 _PushButtonMidPtOnSurf = NULL;
 _PushButtonProjection = NULL;
 _PushButtonStartOtherCmd = NULL;
 _PushButtonCompass = NULL;
 _PushButtonReadTxt = NULL;
 _PushButton3DView = NULL;
//END CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
}



void TestDlg::Build()
{
//  TODO: This call builds your dialog from the layout declaration file
//  -------------------------------------------------------------------

//CAA2 WIZARD WIDGET CONSTRUCTION SECTION
 _LabelLine = new CATDlgLabel(this, "LabelLine");
_LabelLine -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _Container002 = new CATDlgContainer(this, "Container002");
 _Container002 -> SetRectDimensions(1, 1, 1, 10);
_Container002 -> SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
 _SelectorListLine = new CATDlgSelectorList(this, "SelectorListLine");
 _SelectorListLine -> SetVisibleTextHeight(1);
_SelectorListLine -> SetGridConstraints(0, 2, 1, 1, CATGRID_4SIDES);
 _Container003 = new CATDlgContainer(this, "Container003");
 _Container003 -> SetRectDimensions(1, 1, 1, 10);
_Container003 -> SetGridConstraints(0, 3, 1, 1, CATGRID_4SIDES);
 _PushButtonCOUT = new CATDlgPushButton(this, "PushButtonCOUT");
_PushButtonCOUT -> SetGridConstraints(2, 4, 1, 1, CATGRID_4SIDES);
 _Container004 = new CATDlgContainer(this, "Container004");
 _Container004 -> SetRectDimensions(1, 1, 10, 10);
_Container004 -> SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);
 _LabelAxis = new CATDlgLabel(this, "LabelAxis");
_LabelAxis -> SetGridConstraints(2, 0, 1, 1, CATGRID_4SIDES);
 _SelectorListFace = new CATDlgSelectorList(this, "SelectorListFace");
 _SelectorListFace -> SetVisibleTextHeight(1);
_SelectorListFace -> SetGridConstraints(2, 2, 1, 1, CATGRID_4SIDES);
 _PushButtonMidPtOnSurf = new CATDlgPushButton(this, "PushButtonMidPtOnSurf");
_PushButtonMidPtOnSurf -> SetGridConstraints(3, 4, 1, 1, CATGRID_4SIDES);
 _PushButtonProjection = new CATDlgPushButton(this, "PushButtonProjection");
_PushButtonProjection -> SetGridConstraints(4, 4, 1, 1, CATGRID_4SIDES);
 _PushButtonStartOtherCmd = new CATDlgPushButton(this, "PushButtonStartOtherCmd");
_PushButtonStartOtherCmd -> SetGridConstraints(5, 4, 1, 1, CATGRID_4SIDES);
 _PushButtonCompass = new CATDlgPushButton(this, "PushButtonCompass");
_PushButtonCompass -> SetGridConstraints(6, 4, 1, 1, CATGRID_4SIDES);
 _PushButtonReadTxt = new CATDlgPushButton(this, "PushButtonReadTxt");
_PushButtonReadTxt -> SetGridConstraints(7, 4, 1, 1, CATGRID_4SIDES);
 _PushButton3DView = new CATDlgPushButton(this, "PushButton3DView");
_PushButton3DView -> SetGridConstraints(8, 4, 1, 1, CATGRID_4SIDES);
//END CAA2 WIZARD WIDGET CONSTRUCTION SECTION

//CAA2 WIZARD CALLBACK DECLARATION SECTION
//END CAA2 WIZARD CALLBACK DECLARATION SECTION

_SelectorListLine->SetLine("No Select",-1);
_SelectorListFace->SetLine("No Select",-1);

}

CATDlgSelectorList* TestDlg::GetSelectListLine()
{
	return _SelectorListLine;
}

CATDlgPushButton* TestDlg::GetPushButtonCOUT()
{
	return _PushButtonCOUT;
}

CATDlgSelectorList* TestDlg::GetSelectListFace()
{
	return _SelectorListFace;
}

CATDlgPushButton* TestDlg::GetPushButtonMidPtOnSurf()
{
	return _PushButtonMidPtOnSurf;
}

CATDlgPushButton* TestDlg::GetPushButtonProjection()
{
	return _PushButtonProjection;
}

CATDlgPushButton* TestDlg::GetPushButtonStartOtherCmd()
{
	return _PushButtonStartOtherCmd;
}

CATDlgPushButton* TestDlg::GetPushButtonCompassTest()
{
	return _PushButtonCompass;
}

CATDlgPushButton* TestDlg::GetPushButtonReadTxt()
{
	return _PushButtonReadTxt;
}

CATDlgPushButton* TestDlg::GetPushButton3DView()
{
	return _PushButton3DView;
}