// COPYRIGHT Dassault Systemes 2020
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework TestTreeViewAddinFrm
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  Apr 2020  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
// DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
AddPrereqComponent("System",Protected);
AddPrereqComponent("GSMInterfaces",Protected);
AddPrereqComponent("ProductStructureUI",Protected);
AddPrereqComponent("PartInterfaces",Protected);
// END WIZARD EDITION ZONE
AddPrereqComponent("ApplicationFrame",Public);
