// COPYRIGHT Dassault Systemes 2014
//===================================================================
//
// ClsOfExcelOperation.h
// Header definition of ClsOfExcelOperation
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  May 2014  Creation: Code generated by the CAA wizard  rui.zhang
//===================================================================
#ifndef ClsOfExcelOperation_H
#define ClsOfExcelOperation_H

//Local
#include "ModPubExcel.h"
#include <afx.h>

//System
#include "CATBaseUnknown.h"
#include "CATUnicodeString.h"
#include "CATListOfCATUnicodeString.h"

#define EXCEL_MAX_LINE 4096

//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* Do not use the @href ClsOfExcelOperation constructor to
* do such and such but instead...
*
* @example
*  // example is optional
*  pObject = new ClsOfExcelOperation;
*  pObject->SetXXX(...);
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class ExportedByModPubExcel ClsOfExcelOperation
{
  //CATDeclareClass;

  public:

  // Standard constructors and destructors
  // -------------------------------------
     ClsOfExcelOperation ();
	 ClsOfExcelOperation (CATUnicodeString strFilePath);

     virtual ~ClsOfExcelOperation ();
	 HRESULT GetExcelInformation(CATUnicodeString strFilePath, CATLISTV(CATUnicodeString) &listOfstrNo, CATLISTV(CATUnicodeString) &listOfstrPartNum, CATLISTV(CATUnicodeString) &listOfstrInst);
	 HRESULT WriteExcel(CATUnicodeString strSavePath, CATLISTV(CATUnicodeString) listOfstrNo, CATLISTV(CATUnicodeString) listOfstrPartNum, CATLISTV(CATUnicodeString) listOfstrInst);
	 HRESULT WriteAsNewExcel(CATUnicodeString strTemplatePath, CATUnicodeString strSavePath, CATLISTV(CATUnicodeString) listOfstrNo, CATLISTV(CATUnicodeString) listOfstrPartNum, CATLISTV(CATUnicodeString) listOfstrInst);
private:

	  void *_pExcelOperation;
};

//-----------------------------------------------------------------------

#endif
