// COPYRIGHT Dassault Systemes 2019
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework GeneralClassFrm
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  Jan 2019  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
// DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
AddPrereqComponent("System",Protected);
// END WIZARD EDITION ZONE
AddPrereqComponent("ApplicationFrame",Protected);
AddPrereqComponent("ProductStructure",Protected);
AddPrereqComponent("ObjectModelerBase",Protected);
AddPrereqComponent("Dialog",Public);
AddPrereqComponent("Visualization",Public);
AddPrereqComponent("ObjectModelerNavigator",Public);
AddPrereqComponent("CATIAApplicationFrame",Public);
AddPrereqComponent("MecModInterfaces",Public);
AddPrereqComponent("NewTopologicalObjects",Public);
AddPrereqComponent("GeometricObjects",Public);
AddPrereqComponent("Mathematics",Public);
AddPrereqComponent("MechanicalModelerUI",Public);
AddPrereqComponent("ObjectSpecsModeler",Public);
AddPrereqComponent("KnowledgeInterfaces",Protected);
AddPrereqComponent("TopologicalOperators",Public);
AddPrereqComponent("InteractiveInterfaces",Public);
AddPrereqComponent("InfInterfaces",Public);
AddPrereqComponent("DraftingInterfaces",Public);
AddPrereqComponent("SketcherInterfaces",Protected);
AddPrereqComponent("SpaceAnalysisInterfaces",Public);
AddPrereqComponent("YFAirventXMLFrm",Public);
AddPrereqComponent("GeometricOperators",Public);
AddPrereqComponent("VPMInterfaces",Public);
AddPrereqComponent("MechanicalModeler",Public);
AddPrereqComponent("BasicTopologicalOpe",Public);
AddPrereqComponent("GSMInterfaces",Public);
