// COPYRIGHT Dassault Systemes 2020
//===================================================================
//
// TestEnvelopeCmd.h
// The state chart based command: TestEnvelopeCmd
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   STATECOMMAND
//End CAA2 Wizard Generation Report
//
//  May 2020  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#ifndef TestEnvelopeCmd_H
#define TestEnvelopeCmd_H

#include "CATStateCommand.h"
#include "CATBoolean.h"

#include "TestEnvelopeDlg.h"
#include "GeneralClass.h"

#include "CATDynTransformation.h"
#include "CATDynBoolean.h"

class CATIndicationAgent;

//----------------------------------------------------------------------

/**
 * Describe your command here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog engine framework.
 * (consult base class description).
 */
class TestEnvelopeCmd: public CATStateCommand
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( TestEnvelopeCmd, CATStateCommand )

  public:

  TestEnvelopeCmd();
  virtual ~TestEnvelopeCmd();

    /**
     * Defines the command automata.
     * <br>
     * <i>(states, transitions and agents)</i>
     */
  virtual void     BuildGraph();

    /**
     * Action associated to state transitions.
     */
  virtual CATBoolean  ActionOne(void * data);
  CATBoolean ActionExit(void * data);
  CATBoolean ActionOK(void * data);
  void selectObjAFunc(void * data);
  void selectObjBFunc(void * data);
  void TransToSelectA(void * data);
  void TransToSelectB(void * data);
  HRESULT CreateEnvelope(CATBaseUnknown_var ispBUObj,CATBaseUnknown_var ispBUCurve);
private:

	  TestEnvelopeDlg		*_pDlg;

	  CATFrmEditor			*_pEditor;

	  CATHSO				*_pHSO;

	  GeneralClass			*_pGeneralCls;

	  CATFeatureImportAgent * _pSelAAgent;

	  CATFeatureImportAgent * _pSelBAgent;

	  CATDialogAgent		* _pSelAFieldAgent;

	  CATDialogAgent		* _pSelBFieldAgent;

	  CATBaseUnknown_var	_spBUSelectA;

	  CATBaseUnknown_var	_spBUSelectB;

	  CATIProduct_var		_spiProdSelA;

	  CATIProduct_var		_spiProdSelB;

};

//----------------------------------------------------------------------

#endif
