// COPYRIGHT Dassault Systemes 2019
//===================================================================
//
// UpdateDataBaseDlg.cpp
// The dialog : UpdateDataBaseDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Jan 2019  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#include "UpdateDataBaseDlg.h"
#include "CATApplicationFrame.h"
#include "CATDlgGridConstraints.h"
#include "CATMsgCatalog.h"
#ifdef UpdateDataBaseDlg_ParameterEditorInclude
#include "CATIParameterEditorFactory.h"
#include "CATIParameterEditor.h"
#include "CATICkeParm.h"
#endif




//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
UpdateDataBaseDlg::UpdateDataBaseDlg() :
  CATDlgDialog ((CATApplicationFrame::GetApplicationFrame())->GetMainWindow(),
//CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
"UpdateDataBaseDlg",CATDlgWndBtnClose|CATDlgGridLayout
//END CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
                               )
{
//CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
 _MultiListPartList = NULL;
 _Frame002 = NULL;
 _PushButtonRefresh = NULL;
 _Container004 = NULL;
 _PushButtonWriteExcel = NULL;
 _Container006 = NULL;
//END CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
UpdateDataBaseDlg::~UpdateDataBaseDlg()
{
//  Do not delete the control elements of your dialog: 
//     this is done automatically
//  --------------------------------------------------
//CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
 _MultiListPartList = NULL;
 _Frame002 = NULL;
 _PushButtonRefresh = NULL;
 _Container004 = NULL;
 _PushButtonWriteExcel = NULL;
 _Container006 = NULL;
//END CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
}



void UpdateDataBaseDlg::Build()
{
//  TODO: This call builds your dialog from the layout declaration file
//  -------------------------------------------------------------------

//CAA2 WIZARD WIDGET CONSTRUCTION SECTION
 _MultiListPartList = new CATDlgMultiList(this, "MultiListPartList");
 CATUnicodeString MultiListPartListTitles [ 2 ];
 MultiListPartListTitles[0] = CATMsgCatalog::BuildMessage("UpdateDataBaseDlg", "MultiListPartList.ColumnTitle1");
 MultiListPartListTitles[1] = CATMsgCatalog::BuildMessage("UpdateDataBaseDlg", "MultiListPartList.ColumnTitle2");
 _MultiListPartList -> SetColumnTitles(2, MultiListPartListTitles);
 _MultiListPartList -> SetVisibleColumnCount( 1 );
 _MultiListPartList->SetColumnTextWidth (0, 10);
 _MultiListPartList->SetColumnTextWidth (1, 5);
_MultiListPartList -> SetGridConstraints(0, 2, 1, 1, CATGRID_4SIDES);
 _Frame002 = new CATDlgFrame(this, "Frame002", CATDlgFraNoFrame|CATDlgGridLayout);
_Frame002 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _PushButtonRefresh = new CATDlgPushButton(_Frame002, "PushButtonRefresh");
_PushButtonRefresh -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _Container004 = new CATDlgContainer(_Frame002, "Container004");
 _Container004 -> SetRectDimensions(1, 1, 5, 5);
_Container004 -> SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);
 _PushButtonWriteExcel = new CATDlgPushButton(_Frame002, "PushButtonWriteExcel");
_PushButtonWriteExcel -> SetGridConstraints(2, 0, 1, 1, CATGRID_4SIDES);
 _Container006 = new CATDlgContainer(this, "Container006");
 _Container006 -> SetRectDimensions(1, 1, 5, 10);
_Container006 -> SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
//END CAA2 WIZARD WIDGET CONSTRUCTION SECTION

//CAA2 WIZARD CALLBACK DECLARATION SECTION
//END CAA2 WIZARD CALLBACK DECLARATION SECTION

}

CATDlgPushButton *UpdateDataBaseDlg::GetPushButtonRefresh()
{
	return _PushButtonRefresh;
}

CATDlgPushButton *UpdateDataBaseDlg::GetPushButtonWriteExcel()
{
	return _PushButtonWriteExcel;
}

CATDlgMultiList *UpdateDataBaseDlg::GetMultiListPartList()
{
	return _MultiListPartList;
}