// COPYRIGHT Dassault Systemes 2019
//===================================================================
//
// RPSaddin.cpp
// Provide implementation to interface
//    CATIPRDWorkshopAddin
//    CATIPrtWksAddin
//    CATIWorkbenchAddin
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Jan 2019  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#include "RPSaddin.h"
 
CATImplementClass(RPSaddin,
                  Implementation,
                  CATBaseUnknown,
                  CATnull );
 
MacDeclareHeader(RPSaddinHdr);

//-----------------------------------------------------------------------------
// RPSaddin : constructor
//-----------------------------------------------------------------------------
RPSaddin::RPSaddin():
    CATBaseUnknown()
{
}

//-----------------------------------------------------------------------------
// RPSaddin : destructor
//-----------------------------------------------------------------------------
RPSaddin::~RPSaddin()
{
}
 
// Link the implementation to its interface
// ---------------------------------------



//TIE or TIEchain definitions
#include "TIE_CATIPRDWorkshopAddin.h"
TIE_CATIPRDWorkshopAddin(RPSaddin);
#include "TIE_CATIPrtWksAddin.h"
TIE_CATIPrtWksAddin(RPSaddin);
//#include "TIE_CATIWorkbenchAddin.h"
//TIE_CATIWorkbenchAddin(RPSaddin);


//Methods implementation

//-----------------------------------------------------------------------------
// Implements CATIWorkbenchAddin::CreateCommands
//-----------------------------------------------------------------------------
void RPSaddin::CreateCommands ()
{
	new RPSaddinHdr("UpdateDataBase","UpdateDataBaseMod","UpdateDataBaseCmd", (void*)NULL);
	new RPSaddinHdr("RPSInsert","RPSInsertMod","RPSInsertCmd", (void*)NULL);
	return;
}

//-----------------------------------------------------------------------------
// Implements CATIWorkbenchAddin::CreateToolbars
//-----------------------------------------------------------------------------
CATCmdContainer * RPSaddin::CreateToolbars ()
{
	//
	NewAccess (CATCmdContainer,pRPSTlb,RPSCreation);
	//
	NewAccess (CATCmdStarter,pUpdateDB,UpdateDataBase);
	SetAccessCommand (pUpdateDB,"UpdateDataBase");
	SetAccessChild(pRPSTlb,pUpdateDB);
	//
	NewAccess (CATCmdStarter,pRPSInsert,RPSInsert);
	SetAccessCommand (pRPSInsert,"RPSInsert");
	SetAccessNext(pUpdateDB,pRPSInsert);
	//
	AddToolbarView(pRPSTlb,1,UnDock);

    return pRPSTlb;
}

