// COPYRIGHT Dassault Systemes 2018
//===================================================================
//
// RPSCreationDlg.cpp
// The dialog : RPSCreationDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Dec 2018  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#include "RPSCreationDlg.h"
#include "CATApplicationFrame.h"
#include "CATDlgGridConstraints.h"
#include "CATMsgCatalog.h"
#ifdef RPSCreationDlg_ParameterEditorInclude
#include "CATIParameterEditorFactory.h"
#include "CATIParameterEditor.h"
#include "CATICkeParm.h"
#endif




//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
RPSCreationDlg::RPSCreationDlg() :
  CATDlgDialog ((CATApplicationFrame::GetApplicationFrame())->GetMainWindow(),
//CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
"RPSCreationDlg",CATDlgWndBtnClose|CATDlgGridLayout
//END CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
                               )
{
//CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
 _Frame001 = NULL;
 _PushButtonRPSList = NULL;
 _Frame003 = NULL;
 _MultiListRPSList = NULL;
 _Container006 = NULL;
//END CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
RPSCreationDlg::~RPSCreationDlg()
{
//  Do not delete the control elements of your dialog: 
//     this is done automatically
//  --------------------------------------------------
//CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
 _Frame001 = NULL;
 _PushButtonRPSList = NULL;
 _Frame003 = NULL;
 _MultiListRPSList = NULL;
 _Container006 = NULL;
//END CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
}



void RPSCreationDlg::Build()
{
//  TODO: This call builds your dialog from the layout declaration file
//  -------------------------------------------------------------------

//CAA2 WIZARD WIDGET CONSTRUCTION SECTION
 _Frame001 = new CATDlgFrame(this, "Frame001", CATDlgFraNoFrame|CATDlgGridLayout);
_Frame001 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _PushButtonRPSList = new CATDlgPushButton(_Frame001, "PushButtonRPSList");
_PushButtonRPSList -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _Frame003 = new CATDlgFrame(this, "Frame003", CATDlgFraNoFrame|CATDlgGridLayout);
_Frame003 -> SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
 _MultiListRPSList = new CATDlgMultiList(_Frame003, "MultiListRPSList");
 CATUnicodeString MultiListRPSListTitles [ 5 ];
 MultiListRPSListTitles[0] = CATMsgCatalog::BuildMessage("RPSCreationDlg", "Frame003.MultiListRPSList.ColumnTitle1");
 MultiListRPSListTitles[1] = CATMsgCatalog::BuildMessage("RPSCreationDlg", "Frame003.MultiListRPSList.ColumnTitle2");
 MultiListRPSListTitles[2] = CATMsgCatalog::BuildMessage("RPSCreationDlg", "Frame003.MultiListRPSList.ColumnTitle3");
 MultiListRPSListTitles[3] = CATMsgCatalog::BuildMessage("RPSCreationDlg", "Frame003.MultiListRPSList.ColumnTitle4");
 MultiListRPSListTitles[4] = CATMsgCatalog::BuildMessage("RPSCreationDlg", "Frame003.MultiListRPSList.ColumnTitle5");
 _MultiListRPSList -> SetColumnTitles(5, MultiListRPSListTitles);
 _MultiListRPSList -> SetVisibleColumnCount( 5 );
 _MultiListRPSList->SetColumnTextWidth (0, 15);
 _MultiListRPSList->SetColumnTextWidth (1, 5);
 _MultiListRPSList->SetColumnTextWidth (2, 10);
 _MultiListRPSList->SetColumnTextWidth (3, 10);
 _MultiListRPSList->SetColumnTextWidth (4, 10);
_MultiListRPSList -> SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
 _Container006 = new CATDlgContainer(_Frame003, "Container006");
 _Container006 -> SetRectDimensions(1, 1, 5, 5);
_Container006 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
//END CAA2 WIZARD WIDGET CONSTRUCTION SECTION

//CAA2 WIZARD CALLBACK DECLARATION SECTION
//END CAA2 WIZARD CALLBACK DECLARATION SECTION

}

CATDlgPushButton *RPSCreationDlg::GetPushButtonRPSList()
{
	return _PushButtonRPSList;
}

CATDlgMultiList *RPSCreationDlg::GetMultiListRPSList()
{
	return _MultiListRPSList;
}