// COPYRIGHT Dassault Systemes 2013
//===================================================================
//
// DumETempPlaneInstance.cpp
// Provide implementation to interface
//    CATICreateInstance
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Aug 2013  Creation: Code generated by the CAA wizard  
//===================================================================
#include "DumETempPlaneInstance.h"
#include "DumTempPlaneComp.h"
 
CATImplementClass(DumETempPlaneInstance,
                  DataExtension,
                  CATBaseUnknown,
                  DumTempPlaneComp );
 

//-----------------------------------------------------------------------------
// DumETempPlaneInstance : constructor
//-----------------------------------------------------------------------------
DumETempPlaneInstance::DumETempPlaneInstance():
    CATBaseUnknown()
{
}

//-----------------------------------------------------------------------------
// DumETempPlaneInstance : destructor
//-----------------------------------------------------------------------------
DumETempPlaneInstance::~DumETempPlaneInstance()
{
}
 
// Link the implementation to its interface
// ---------------------------------------



//TIE or TIEchain definitions
#include "TIE_CATICreateInstance.h"
TIE_CATICreateInstance( DumETempPlaneInstance);


//Methods implementation

//-----------------------------------------------------------------------------
// Implements CATICreateInstance::CreateInstance
//-----------------------------------------------------------------------------
HRESULT __stdcall DumETempPlaneInstance::CreateInstance (void ** oPPV)
{
	DumTempPlaneComp *pVisPointModel = new DumTempPlaneComp();

	if( NULL == pVisPointModel ) return (E_OUTOFMEMORY);

	*oPPV = (void *)pVisPointModel;

   return S_OK;
}

