// COPYRIGHT Dassault Systemes 2019
//===================================================================
//
// TestCrossDocDlg.h
// The dialog : TestCrossDocDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   DIALOG
//End CAA2 Wizard Generation Report
//
//  Jun 2019  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#ifndef TestCrossDocDlg_H
#define TestCrossDocDlg_H

#include "CATDlgDialog.h"
#include "CATDlgInclude.h"

//----------------------------------------------------------------------

/**
 * Describe the purpose of your panel here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog framework.
 * (consult base class description).
 */
class TestCrossDocDlg: public CATDlgDialog
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( TestCrossDocDlg, CATDlgDialog )

  public:

  TestCrossDocDlg();
  virtual ~TestCrossDocDlg();

  void Build ();

  CATDlgSelectorList* GetSelectorListProduct();
  CATDlgSelectorList* GetSelectorListMultiSelect();
  protected:

  private:


//CAA2 WIZARD WIDGET DECLARATION SECTION
 CATDlgLabel*      _Label001;
 CATDlgSelectorList*      _SelectorListProduct;
 CATDlgContainer*      _Container002;
 CATDlgSelectorList*      _SelectorListMultiSelect;
//END CAA2 WIZARD WIDGET DECLARATION SECTION
};

//----------------------------------------------------------------------

#endif
