// COPYRIGHT Dassault Systemes 2019
//===================================================================
//
// GridView2DDlg.cpp
// The dialog : GridView2DDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Jan 2019  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#include "GridView2DDlg.h"
#include "CATApplicationFrame.h"
#include "CATDlgGridConstraints.h"
#include "CATMsgCatalog.h"
#ifdef GridView2DDlg_ParameterEditorInclude
#include "CATIParameterEditorFactory.h"
#include "CATIParameterEditor.h"
#include "CATICkeParm.h"
#endif




//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
GridView2DDlg::GridView2DDlg() :
  CATDlgDialog ((CATApplicationFrame::GetApplicationFrame())->GetMainWindow(),
//CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
"GridView2DDlg",CATDlgGridLayout
//END CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
                               )
{
//CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
 _FrameNavi2DView = NULL;
//END CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
GridView2DDlg::~GridView2DDlg()
{
//  Do not delete the control elements of your dialog: 
//     this is done automatically
//  --------------------------------------------------
//CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
 _FrameNavi2DView = NULL;
//END CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
}





void GridView2DDlg::Build()
{
//  TODO: This call builds your dialog from the layout declaration file
//  -------------------------------------------------------------------

//CAA2 WIZARD WIDGET CONSTRUCTION SECTION
 _FrameNavi2DView = new CATDlgFrame(this, "FrameNavi2DView", CATDlgFraNoFrame|CATDlgGridLayout);
_FrameNavi2DView -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
//END CAA2 WIZARD WIDGET CONSTRUCTION SECTION

//CAA2 WIZARD CALLBACK DECLARATION SECTION
//END CAA2 WIZARD CALLBACK DECLARATION SECTION

_pNavi2DViewer = new CATNavigation2DViewer(_FrameNavi2DView,"View 2D",CATDlgFraNoFrame|CATDlgFraNoTitle);
_pNavi2DViewer->SetGridConstraints(0,0,1,1,CATGRID_4SIDES);
_pNavi2DViewer->SetBackgroundColor(0.2f,0.2f,0.5f);
}

CATNavigation2DViewer* GridView2DDlg::GetNavi2DViewer()
{
	return _pNavi2DViewer;
}

