// COPYRIGHT Dassault Systemes 2021
//===================================================================
//
// TestDlg.cpp
// The dialog : TestDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Mar 2021  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#include "TestDlg.h"
#include "CATApplicationFrame.h"
#include "CATDlgGridConstraints.h"
#include "CATMsgCatalog.h"
#ifdef TestDlg_ParameterEditorInclude
#include "CATIParameterEditorFactory.h"
#include "CATIParameterEditor.h"
#include "CATICkeParm.h"
#endif




//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
TestDlg::TestDlg() :
  CATDlgDialog ((CATApplicationFrame::GetApplicationFrame())->GetMainWindow(),
//CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
"TestDlg",CATDlgGridLayout
//END CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
                               )
{
//CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
 _Frame001 = NULL;
 _Container006 = NULL;
 _Frame002 = NULL;
 _Label004 = NULL;
 _SelectorList005 = NULL;
//END CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
TestDlg::~TestDlg()
{
//  Do not delete the control elements of your dialog: 
//     this is done automatically
//  --------------------------------------------------
//CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
 _Frame001 = NULL;
 _Container006 = NULL;
 _Frame002 = NULL;
 _Label004 = NULL;
 _SelectorList005 = NULL;
//END CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
}



void TestDlg::Build()
{
//  TODO: This call builds your dialog from the layout declaration file
//  -------------------------------------------------------------------

//CAA2 WIZARD WIDGET CONSTRUCTION SECTION
 _Frame001 = new CATDlgFrame(this, "Frame001", CATDlgFraNoTitle|CATDlgGridLayout);
_Frame001 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _Container006 = new CATDlgContainer(_Frame001, "Container006");
 _Container006 -> SetRectDimensions(1, 1, 300, 200);
_Container006 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _Frame002 = new CATDlgFrame(this, "Frame002", CATDlgFraNoTitle|CATDlgGridLayout);
_Frame002 -> SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
 _Label004 = new CATDlgLabel(_Frame002, "Label004");
_Label004 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _SelectorList005 = new CATDlgSelectorList(_Frame002, "SelectorList005");
 _SelectorList005 -> SetVisibleTextHeight(1);
 _SelectorList005 -> SetVisibleTextWidth(15);
_SelectorList005 -> SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
//END CAA2 WIZARD WIDGET CONSTRUCTION SECTION

//CAA2 WIZARD CALLBACK DECLARATION SECTION
//END CAA2 WIZARD CALLBACK DECLARATION SECTION

}

