// COPYRIGHT Dassault Systemes 2020
//===================================================================
//
// TstIPoint.h
// Define the TstIPoint interface
//
//===================================================================
//
// Usage notes:
//   New interface: describe its use here
//
//===================================================================
//
//  Apr 2020  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#ifndef TstIPoint_H
#define TstIPoint_H

#include "TestExtendPtItfCPP.h"
#include "CATBaseUnknown.h"

#ifndef LOCAL_DEFINITION_FOR_IID
extern ExportedByTestExtendPtItfCPP IID IID_TstIPoint;
#else
extern "C" const IID IID_TstIPoint ;
#endif

//------------------------------------------------------------------

/**
* Interface representing xxx.
*
* <br><b>Role</b>: Components that implement
* TstIPoint are ...
* <p>
* Do not use the TstIPoint interface for such and such

*
* @example
*  // example is optional
*  TstIPoint* currentDisplay = NULL;
*  rc = window-&gt;QueryInterface(IID_TstIPoint,
*                                     (void**) &amp;currentDisplay);
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class ExportedByTestExtendPtItfCPP TstIPoint: public CATBaseUnknown
{
  CATDeclareInterface;

  public:

    /**
     * Remember that interfaces define only virtual pure methods.
     * Dont forget to document your methods.
     * <dl>
     * <dt><b>Example:</b>
     * <pre>
     *       
           *   MyFunction does this and that
           *   @param Arg1
           *      The first argument of MyFunction.
           *   @return
           *      Error code of function.
           * 
     * virtual int MyFunction (int Arg1) = 0;
     * </pre>
     * </dl>
     */

  // No constructors or destructors on this pure virtual base class
  // --------------------------------------------------------------

	  virtual HRESULT GetX(double &oX)	= 0;
	  virtual HRESULT SetX(double iX)	= 0;
	  virtual HRESULT GetY(double &oY)	= 0;
	  virtual HRESULT SetY(double iY)	= 0;
	  virtual HRESULT GetZ(double &oZ)	= 0;
	  virtual HRESULT SetZ(double iZ)	= 0;
};

//------------------------------------------------------------------
CATDeclareHandler(TstIPoint,CATBaseUnknown);
#endif
