# COPYRIGHT Dassault Systemes 2021
#======================================================================
# Imakefile for module TJMBeginApplicationM.m
#======================================================================
#
#  Mar 2021  Creation: Code generated by the CAA wizard  Administrator
#======================================================================
#
# LOAD MODULE 
#
BUILT_OBJECT_TYPE=LOAD MODULE 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0GROUP \
DI0PANV2 
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES)	\
JS0FM \
CATObjectModelerBase \
CATApplicationFrame	\
CATIAApplicationFrame	\
CATVisualization	\
CATMecModInterfaces		\
CATObjectModelerBase	\
CATObjectSpecsModeler	\
CATMathematics	\
CATProductStructure1	\

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
LOCAL_LDFLAGS = $(SUB_WIN)
