// COPYRIGHT Dassault Systemes 2020
//===================================================================
//
// TestProgressBarCmd.h
// The state chart based command: TestProgressBarCmd
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   STATECOMMAND
//End CAA2 Wizard Generation Report
//
//  Jan 2020  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#ifndef TestProgressBarCmd_H
#define TestProgressBarCmd_H

#include "CATStateCommand.h"
#include "CATBoolean.h"
#include "TestProgressBarDlg.h"

class CATIndicationAgent;

//----------------------------------------------------------------------

/**
 * Describe your command here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog engine framework.
 * (consult base class description).
 */
class TestProgressBarCmd: public CATStateCommand
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( TestProgressBarCmd, CATStateCommand )

  public:

  TestProgressBarCmd();
  virtual ~TestProgressBarCmd();

    /**
     * Defines the command automata.
     * <br>
     * <i>(states, transitions and agents)</i>
     */
  virtual void     BuildGraph();

    /**
     * Action associated to state transitions.
     */
  virtual CATBoolean  ActionOne(void * data);
  CATBoolean ExitCmd(void * data);
  CATBoolean ActionOK(void * data);
private:

  TestProgressBarDlg	*_pDlg;

  int					_iCountClick;
};

//----------------------------------------------------------------------

#endif
