// COPYRIGHT Dassault Systemes 2019
//===================================================================
//
// TestCrvRadiusCmd.h
// The state chart based command: TestCrvRadiusCmd
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   STATECOMMAND
//End CAA2 Wizard Generation Report
//
//  Nov 2019  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#ifndef TestCrvRadiusCmd_H
#define TestCrvRadiusCmd_H

#include "CATStateCommand.h"
#include "CATBoolean.h"
#include "TestCrvRadiusDlg.h"
#include "GeneralClass.h"

class CATIndicationAgent;

//----------------------------------------------------------------------

/**
 * Describe your command here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog engine framework.
 * (consult base class description).
 */
class TestCrvRadiusCmd: public CATStateCommand
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( TestCrvRadiusCmd, CATStateCommand )

  public:

  TestCrvRadiusCmd();
  virtual ~TestCrvRadiusCmd();

    /**
     * Defines the command automata.
     * <br>
     * <i>(states, transitions and agents)</i>
     */
  virtual void     BuildGraph();

    /**
     * Action associated to state transitions.
     */
  virtual CATBoolean  ActionOne(void * data);
  CATBoolean ExitCmd(void * data);
  void ActionSurfaceSelect(void * data);
private:

	  TestCrvRadiusDlg			*_pDlg;

	  GeneralClass				*_pGeneralCls;

	  CATFeatureImportAgent		*_pSurfaceAgent;

	  CATDialogAgent			*_pSurfaceFieldAgent;
  
};

//----------------------------------------------------------------------

#endif
