// COPYRIGHT Dassault Systemes 2018
//===================================================================
//
// WriteExcelDlg.h
// The dialog : WriteExcelDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   DIALOG
//End CAA2 Wizard Generation Report
//
//  Dec 2018  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#ifndef WriteExcelDlg_H
#define WriteExcelDlg_H

#include "CATDlgDialog.h"
#include "CATDlgInclude.h"

//----------------------------------------------------------------------

/**
 * Describe the purpose of your panel here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog framework.
 * (consult base class description).
 */
class WriteExcelDlg: public CATDlgDialog
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( WriteExcelDlg, CATDlgDialog )

  public:

  WriteExcelDlg();
  virtual ~WriteExcelDlg();

  void Build ();

  CATDlgEditor* GetEditorSavePath();

  CATDlgPushButton* GetPushButtonSelectPath();

  CATDlgPushButton* GetPushButtonReadExcel();

  protected:

  private:


//CAA2 WIZARD WIDGET DECLARATION SECTION
 CATDlgContainer*      _Container003;
 CATDlgContainer*      _Container004;
 CATDlgLabel*      _LabelSavePath;
 CATDlgEditor*      _EditorSavePath;
 CATDlgPushButton*      _PushButtonSelectPath;
 CATDlgContainer*      _Container008;
 CATDlgPushButton*      _PushButtonReadXls;
//END CAA2 WIZARD WIDGET DECLARATION SECTION
};

//----------------------------------------------------------------------

#endif
