// COPYRIGHT Dassault Systemes 2018
//===================================================================
//
// DrwSetColorDlg.h
// The dialog : DrwSetColorDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   DIALOG
//End CAA2 Wizard Generation Report
//
//  Dec 2018  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#ifndef DrwSetColorDlg_H
#define DrwSetColorDlg_H

#include "CATDlgDialog.h"
#include "CATDlgInclude.h"

//----------------------------------------------------------------------

/**
 * Describe the purpose of your panel here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog framework.
 * (consult base class description).
 */
class DrwSetColorDlg: public CATDlgDialog
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( DrwSetColorDlg, CATDlgDialog )

  public:

  DrwSetColorDlg();
  virtual ~DrwSetColorDlg();

  void Build ();

  CATDlgSelectorList* GetSelectorListObjectSelection();

  CATDlgCombo* GetComboColor();

  CATDlgCombo* GetComboLineType();

  CATDlgCombo* GetComboLintThickness();

  protected:

  private:


//CAA2 WIZARD WIDGET DECLARATION SECTION
 CATDlgLabel*      _LabelObject;
 CATDlgSelectorList*      _SelectorListObjectSelection;
 CATDlgContainer*      _Container009;
 CATDlgLabel*      _LabelColor;
 CATDlgContainer*      _Container011;
 CATDlgCombo*      _ComboColor;
 CATDlgContainer*      _Container012;
 CATDlgLabel*      _LabelLineType;
 CATDlgCombo*      _ComboLineType;
 CATDlgContainer*      _Container015;
 CATDlgLabel*      _LabelLineThickness;
 CATDlgCombo*      _ComboLineThickness;
//END CAA2 WIZARD WIDGET DECLARATION SECTION
};

//----------------------------------------------------------------------

#endif
