// COPYRIGHT Dassault Systemes 2019
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework FrmRPSCreation
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  Jan 2019  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
// DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
AddPrereqComponent("System",Protected);
AddPrereqComponent("ApplicationFrame",Protected);
AddPrereqComponent("MechanicalModelerUI",Protected);
AddPrereqComponent("ProductStructureUI",Protected);
AddPrereqComponent("DialogEngine",Protected);
AddPrereqComponent("Mathematics",Protected);
AddPrereqComponent("Dialog",Protected);
// END WIZARD EDITION ZONE
AddPrereqComponent("MecModInterfaces",Protected);
AddPrereqComponent("ObjectModelerBase",Protected);
AddPrereqComponent("ProductStructure",Protected);
AddPrereqComponent("GMModelInterfaces",Protected);
AddPrereqComponent("FMPublic",Public);
AddPrereqComponent("GSMInterfaces",Protected);
AddPrereqComponent("ObjectSpecsModeler",Protected);
AddPrereqComponent("VisualizationBase",Protected);
AddPrereqComponent("GeometricObjects",Protected);
