// COPYRIGHT Dassault Systemes 2021
//===================================================================
//
// TJMDlgInterApplication.h
// Header definition of TJMDlgInterApplication
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Mar 2021  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#ifndef TJMDlgInterApplication_H
#define TJMDlgInterApplication_H

#include "CATInteractiveApplication.h"
#include "TJMDlgInterWindow.h"

#include "iostream.h"

//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* Do not use the @href TJMDlgInterApplication constructor to
* do such and such but instead...
*
* @example
*  // example is optional
*  pObject = new TJMDlgInterApplication;
*  pObject->SetXXX(...);
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class TJMDlgInterApplication: public CATInteractiveApplication
{
  //CATDeclareClass;

  public:

  // Standard constructors and destructors
  // -------------------------------------
     
	 TJMDlgInterApplication(const CATString& iIdentifier);
     virtual ~TJMDlgInterApplication ();
	 void BeginApplication();
	 int EndApplication();

private:
  // Copy constructor and equal operator
  // -----------------------------------
	TJMDlgInterApplication ();
	TJMDlgInterApplication (TJMDlgInterApplication &);
	TJMDlgInterApplication& operator=(TJMDlgInterApplication&);

};

//-----------------------------------------------------------------------

#endif
