// COPYRIGHT Dassault Systemes 2021
//===================================================================
//
// TJMDlgInterWindow.h
// Header definition of TJMDlgInterWindow
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Mar 2021  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#ifndef TJMDlgInterWindow_H
#define TJMDlgInterWindow_H

#include "CATDlgDocument.h"
#include "iostream.h"
#include "CATInteractiveApplication.h"
#include "CATDlgDialog.h"
#include "CATDlgInclude.h"
#include "CATDlgGridConstraints.h"
#include "TJMCreateViewWindowDlg.h"

#include "CATIPrtPart.h"
#include "CATDocumentServices.h"
#include "CATInit.h"
#include "CATDocument.h"
#include "CATIPrtContainer.h"
#include "CATISpecObject.h"
#include "CATSession.h"
#include "CATSessionServices.h"
#include "CATIEditor.h"
// Visualization Framework
#include "CATNavigation3DViewer.h"
#include "CAT3DBagRep.h"
#include "CAT3DCuboidRep.h"
#include "CAT3DSimpleSphereRep.h"
#include "CAT3DViewpoint.h"

#include "CATIDocRoots.h"
#include "CATIProduct.h"

#include "TJMVisManagerCmdSelector.h"

class CATInteractiveApplication;

//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* Do not use the @href TJMDlgInterWindow constructor to
* do such and such but instead...
*
* @example
*  // example is optional
*  pObject = new TJMDlgInterWindow;
*  pObject->SetXXX(...);
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class TJMDlgInterWindow: public CATDlgDocument
{
  //CATDeclareClass;

	DeclareResource(TJMDlgInterWindow, CATDlgDocument)

  public:

  // Standard constructors and destructors
  // -------------------------------------
     TJMDlgInterWindow (CATInteractiveApplication * iParentCommand);
     virtual ~TJMDlgInterWindow ();

	 void Build();

private:
  // Copy constructor and equal operator
  // -----------------------------------
	void Exit (CATCommand           * iSendingCommand, 
				CATNotification      * iSentNotification, 
				CATCommandClientData   iUsefulData);

	TJMDlgInterWindow ();
	TJMDlgInterWindow (TJMDlgInterWindow &);
	TJMDlgInterWindow& operator=(TJMDlgInterWindow&);
	HRESULT GetProductFromPath(CATUnicodeString istrFilePath,CATBoolean ibDocReadOnly,CATIPrtPart_var &ospiRootPrtPart);
	void CreateViewer();
	void CreateModelRepresentation();
	void VisualizeModel();
	void ShowProduct(CATDocument * ipDoc);
	void ShowModelInTheDialog(CATISpecObject_var spSpecObjectOnMechanicalPart);
	HRESULT InitSession (char *& ipSessionName);
	HRESULT Close(char *& ipSessionName);
	void Attach();
	void Detach();
	HRESULT CreateNavigBox();
	void ExpandAllNode(CATNavigController *pNavigController,CATBaseUnknown_var iRootObject,CATBaseUnknown_var iExpendObject);
	void ExpandCollapseNode(CATNavigController *pNavigController,CATBaseUnknown_var iObject);
	CATInteractiveApplication		*_pApplication;

	// The Top of the representation tree
	CAT3DBagRep               * _pTheModelToDisplay ;

	// The Dialog object to display the model 
	CATNavigation3DViewer     * _p3DViewer ;

	CATDlgFrame				*_pFrame3DView;

	CATDlgContainer			*_pContainer3DViewer;

	CATSession				*_pSession;

	CATDocument				*_pDoc;

	CATBaseUnknown_var		_spBURootObj;

	CATHSO					*_pHSO;
	CATPSO					*_pPSO;

};

//-----------------------------------------------------------------------

#endif
