// COPYRIGHT Dassault Systemes 2019
//===================================================================
//
// DrwAnnotationDlg.cpp
// The dialog : DrwAnnotationDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Jan 2019  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#include "DrwAnnotationDlg.h"
#include "CATApplicationFrame.h"
#include "CATDlgGridConstraints.h"
#include "CATMsgCatalog.h"
#ifdef DrwAnnotationDlg_ParameterEditorInclude
#include "CATIParameterEditorFactory.h"
#include "CATIParameterEditor.h"
#include "CATICkeParm.h"
#endif




//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
DrwAnnotationDlg::DrwAnnotationDlg() :
  CATDlgDialog ((CATApplicationFrame::GetApplicationFrame())->GetMainWindow(),
//CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
"DrwAnnotationDlg",CATDlgGridLayout
//END CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
                               )
{
//CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
 _LabelElement = NULL;
 _Container002 = NULL;
 _SelectorListElement = NULL;
 _Container004 = NULL;
 _LabelTol = NULL;
 _EditorTol = NULL;
//END CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
DrwAnnotationDlg::~DrwAnnotationDlg()
{
//  Do not delete the control elements of your dialog: 
//     this is done automatically
//  --------------------------------------------------
//CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
 _LabelElement = NULL;
 _Container002 = NULL;
 _SelectorListElement = NULL;
 _Container004 = NULL;
 _LabelTol = NULL;
 _EditorTol = NULL;
//END CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
}



void DrwAnnotationDlg::Build()
{
//  TODO: This call builds your dialog from the layout declaration file
//  -------------------------------------------------------------------

//CAA2 WIZARD WIDGET CONSTRUCTION SECTION
 _LabelElement = new CATDlgLabel(this, "LabelElement");
_LabelElement -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _Container002 = new CATDlgContainer(this, "Container002");
 _Container002 -> SetRectDimensions(1, 1, 1, 10);
_Container002 -> SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
 _SelectorListElement = new CATDlgSelectorList(this, "SelectorListElement");
 _SelectorListElement -> SetVisibleTextHeight(1);
_SelectorListElement -> SetGridConstraints(0, 2, 1, 1, CATGRID_4SIDES);
 _Container004 = new CATDlgContainer(this, "Container004");
 _Container004 -> SetRectDimensions(1, 1, 5, 10);
_Container004 -> SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);
 _LabelTol = new CATDlgLabel(this, "LabelTol");
_LabelTol -> SetGridConstraints(2, 0, 1, 1, CATGRID_4SIDES);
 _EditorTol = new CATDlgEditor(this, "EditorTol");
_EditorTol -> SetGridConstraints(2, 2, 1, 1, CATGRID_4SIDES);
//END CAA2 WIZARD WIDGET CONSTRUCTION SECTION

//CAA2 WIZARD CALLBACK DECLARATION SECTION
//END CAA2 WIZARD CALLBACK DECLARATION SECTION

}

CATDlgSelectorList* DrwAnnotationDlg::GetSelectorListElement()
{
	return _SelectorListElement;
}

CATDlgEditor* DrwAnnotationDlg::GetEditorTol()
{
	return _EditorTol;
}