// COPYRIGHT Dassault Systemes 2019
//===================================================================
//
// ProductConstraintsDlg.cpp
// The dialog : ProductConstraintsDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Jan 2019  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#include "ProductConstraintsDlg.h"
#include "CATApplicationFrame.h"
#include "CATDlgGridConstraints.h"
#include "CATMsgCatalog.h"
#ifdef ProductConstraintsDlg_ParameterEditorInclude
#include "CATIParameterEditorFactory.h"
#include "CATIParameterEditor.h"
#include "CATICkeParm.h"
#endif




//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
ProductConstraintsDlg::ProductConstraintsDlg() :
  CATDlgDialog ((CATApplicationFrame::GetApplicationFrame())->GetMainWindow(),
//CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
"ProductConstraintsDlg",CATDlgWndBtnOKCancel|CATDlgGridLayout
//END CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
                               )
{
//CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
 _LabelLine = NULL;
 _Container002 = NULL;
 _Container003 = NULL;
 _LabelFace = NULL;
 _SelectorListSelectLine = NULL;
 _SelectorListSelectFace = NULL;
//END CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
ProductConstraintsDlg::~ProductConstraintsDlg()
{
//  Do not delete the control elements of your dialog: 
//     this is done automatically
//  --------------------------------------------------
//CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
 _LabelLine = NULL;
 _Container002 = NULL;
 _Container003 = NULL;
 _LabelFace = NULL;
 _SelectorListSelectLine = NULL;
 _SelectorListSelectFace = NULL;
//END CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
}



void ProductConstraintsDlg::Build()
{
//  TODO: This call builds your dialog from the layout declaration file
//  -------------------------------------------------------------------

//CAA2 WIZARD WIDGET CONSTRUCTION SECTION
 _LabelLine = new CATDlgLabel(this, "LabelLine");
_LabelLine -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _Container002 = new CATDlgContainer(this, "Container002");
 _Container002 -> SetRectDimensions(1, 1, 5, 10);
_Container002 -> SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
 _Container003 = new CATDlgContainer(this, "Container003");
 _Container003 -> SetRectDimensions(1, 1, 10, 10);
_Container003 -> SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);
 _LabelFace = new CATDlgLabel(this, "LabelFace");
_LabelFace -> SetGridConstraints(2, 0, 1, 1, CATGRID_4SIDES);
 _SelectorListSelectLine = new CATDlgSelectorList(this, "SelectorListSelectLine");
 _SelectorListSelectLine -> SetVisibleTextHeight(1);
 _SelectorListSelectLine -> SetVisibleTextWidth(20);
_SelectorListSelectLine -> SetGridConstraints(0, 2, 1, 1, CATGRID_4SIDES);
 _SelectorListSelectFace = new CATDlgSelectorList(this, "SelectorListSelectFace");
 _SelectorListSelectFace -> SetVisibleTextHeight(1);
_SelectorListSelectFace -> SetGridConstraints(2, 2, 1, 1, CATGRID_4SIDES);
//END CAA2 WIZARD WIDGET CONSTRUCTION SECTION

//CAA2 WIZARD CALLBACK DECLARATION SECTION
//END CAA2 WIZARD CALLBACK DECLARATION SECTION

CATUnicodeString strNoSelect = "No Selection";
_SelectorListSelectLine->SetLine(strNoSelect,-1,CATDlgDataAdd);
_SelectorListSelectFace->SetLine(strNoSelect,-1,CATDlgDataAdd);

int iTabRow = 0;
_SelectorListSelectLine->SetSelect(&iTabRow,1,1);

}

CATDlgSelectorList* ProductConstraintsDlg::GetSelectorListSelectLine()
{
	return _SelectorListSelectLine;
}

CATDlgSelectorList* ProductConstraintsDlg::GetSelectorListSelectFace()
{
	return _SelectorListSelectFace;
}