// COPYRIGHT Dassault Systemes 2021
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework TJMWheelHouseDraftUIFrm
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  Jan 2021  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
// DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
AddPrereqComponent("System",Protected);
AddPrereqComponent("DialogEngine",Protected);
AddPrereqComponent("Mathematics",Protected);
AddPrereqComponent("Dialog",Protected);
AddPrereqComponent("ApplicationFrame",Public);
// END WIZARD EDITION ZONE
