// COPYRIGHT Dassault Systemes 2020
//===================================================================
//
// TestAddin.cpp
// Provide implementation to interface
//    CATIPrtCfgAddin
//    CATIPRDWorkshopAddin
//    CATIShapeDesignWorkshopAddin
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Apr 2020  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#include "TestAddin.h"
 
CATImplementClass(TestAddin,
                  Implementation,
                  CATBaseUnknown,
                  CATnull );
 
MacDeclareHeader(TestAddinHdr)
//-----------------------------------------------------------------------------
// TestAddin : constructor
//-----------------------------------------------------------------------------
TestAddin::TestAddin():
    CATBaseUnknown()
{
}

//-----------------------------------------------------------------------------
// TestAddin : destructor
//-----------------------------------------------------------------------------
TestAddin::~TestAddin()
{
}
 
// Link the implementation to its interface
// ---------------------------------------



//TIE or TIEchain definitions
#include "TIE_CATIPrtCfgAddin.h"
TIE_CATIPrtCfgAddin(TestAddin);
#include "TIE_CATIPRDWorkshopAddin.h"
TIE_CATIPRDWorkshopAddin(TestAddin);
#include "TIE_CATIShapeDesignWorkshopAddin.h"
TIE_CATIShapeDesignWorkshopAddin(TestAddin);


//Methods implementation

void TestAddin::CreateCommands()
{
	new TestAddinHdr("TestTreeView","TestTreeViewMod","TestTreeViewCmd",(void*) NULL);
}

CATCmdContainer* TestAddin::CreateToolbars()
{
	NewAccess(CATCmdContainer,pTestTreeViewTlb,TestTreeViewTlb);

	NewAccess(CATCmdStarter, pTestTreeViewCmd,TestTreeViewCmd);
	SetAccessCommand(pTestTreeViewCmd,"TestTreeView");
	SetAccessChild(pTestTreeViewTlb,pTestTreeViewCmd);

	AddToolbarView(pTestTreeViewTlb,-1, Left);

	return pTestTreeViewTlb;

}