// COPYRIGHT Dassault Systemes 2020
//===================================================================
//
// TestTessellationDlg.h
// The dialog : TestTessellationDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   DIALOG
//End CAA2 Wizard Generation Report
//
//  Mar 2020  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#ifndef TestTessellationDlg_H
#define TestTessellationDlg_H

#include "CATDlgDialog.h"
#include "CATDlgInclude.h"

enum SpinnerType
{
	TesselStep,
	TesselSag,

};

//----------------------------------------------------------------------

/**
 * Describe the purpose of your panel here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog framework.
 * (consult base class description).
 */
class TestTessellationDlg: public CATDlgDialog
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( TestTessellationDlg, CATDlgDialog )

  public:

  TestTessellationDlg();
  virtual ~TestTessellationDlg();

  void Build ();
  CATDlgSelectorList* GetSelectorListSurface();
  CATDlgPushItem* GetRightClickClear();
  CATDlgSpinner *GetSpinnerFunc(int type);
protected:

  private:


//CAA2 WIZARD WIDGET DECLARATION SECTION
 CATDlgLabel*      _Label001;
 CATDlgSelectorList*      _SelectorListSurface;
 CATDlgLabel*      _Label002;
 CATDlgLabel*      _Label003;
 CATDlgSpinner*      _SpinnerStep;
 CATDlgSpinner*      _SpinnerSag;
//END CAA2 WIZARD WIDGET DECLARATION SECTION

 //ÓÒ¼üÏà¹Ø¿Ø¼þ
 CATDlgContextualMenu*		_pRightCLKMenu;
 CATDlgPushItem*			_pRightCLKClear;
};

//----------------------------------------------------------------------

#endif
