// COPYRIGHT Dassault Systemes 2013
//===================================================================
//
// DumETempTextInstance.h
// Provide implementation to interface
//    CATICreateInstance

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//EXTENSION:	DumTempTextComp
//EXTENSIONTYPE:	DataExtension

//    TIE: CATICreateInstance

//End CAA2 Wizard Generation Report
//
//  Jul 2013  Creation: Code generated by the CAA wizard  
//===================================================================
#ifndef DumETempTextInstance_H
#define DumETempTextInstance_H

#include "CATBaseUnknown.h"

//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href CATICreateInstance
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class DumETempTextInstance: public CATBaseUnknown

{
  CATDeclareClass;

  public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
     DumETempTextInstance ();
     virtual ~DumETempTextInstance ();

    /**
     * Implements a function from an interface.
     * @href CATICreateInstance#CreateInstance
     */
     HRESULT __stdcall CreateInstance (void ** oPPV ) ;


  private:
  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  DumETempTextInstance (DumETempTextInstance &);
  DumETempTextInstance& operator=(DumETempTextInstance&);

};

//-----------------------------------------------------------------------

#endif
