// COPYRIGHT Dassault Systemes 2018
//===================================================================
//
// ReadXmlDlg.cpp
// The dialog : ReadXmlDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Dec 2018  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#include "ReadXmlDlg.h"
#include "CATApplicationFrame.h"
#include "CATDlgGridConstraints.h"
#include "CATMsgCatalog.h"
#ifdef ReadXmlDlg_ParameterEditorInclude
#include "CATIParameterEditorFactory.h"
#include "CATIParameterEditor.h"
#include "CATICkeParm.h"
#endif




//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
ReadXmlDlg::ReadXmlDlg() :
  CATDlgDialog ((CATApplicationFrame::GetApplicationFrame())->GetMainWindow(),
//CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
"ReadXmlDlg",CATDlgGridLayout
//END CAA2 WIZARD CONSTRUCTOR DECLARATION SECTION
                               )
{
//CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
 _Frame001 = NULL;
 _LabelDir = NULL;
 _EditorSavePath = NULL;
 _PushButtonSelectPath = NULL;
 _Frame004 = NULL;
 _PushButtonReadXml = NULL;
 _Container007 = NULL;
 _PushButtonWriteXml = NULL;
 _Container009 = NULL;
 _Frame011 = NULL;
 _SelectorListReadXml = NULL;
//END CAA2 WIZARD CONSTRUCTOR INITIALIZATION SECTION
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
ReadXmlDlg::~ReadXmlDlg()
{
//  Do not delete the control elements of your dialog: 
//     this is done automatically
//  --------------------------------------------------
//CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
 _Frame001 = NULL;
 _LabelDir = NULL;
 _EditorSavePath = NULL;
 _PushButtonSelectPath = NULL;
 _Frame004 = NULL;
 _PushButtonReadXml = NULL;
 _Container007 = NULL;
 _PushButtonWriteXml = NULL;
 _Container009 = NULL;
 _Frame011 = NULL;
 _SelectorListReadXml = NULL;
//END CAA2 WIZARD DESTRUCTOR DECLARATION SECTION
}



void ReadXmlDlg::Build()
{
//  TODO: This call builds your dialog from the layout declaration file
//  -------------------------------------------------------------------

//CAA2 WIZARD WIDGET CONSTRUCTION SECTION
 _Frame001 = new CATDlgFrame(this, "Frame001", CATDlgFraNoFrame|CATDlgGridLayout);
_Frame001 -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _LabelDir = new CATDlgLabel(_Frame001, "LabelDir");
_LabelDir -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _EditorSavePath = new CATDlgEditor(_Frame001, "EditorSavePath");
 _EditorSavePath -> SetVisibleTextWidth(30);
_EditorSavePath -> SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
 _PushButtonSelectPath = new CATDlgPushButton(_Frame001, "PushButtonSelectPath");
_PushButtonSelectPath -> SetGridConstraints(0, 2, 1, 1, CATGRID_4SIDES);
 _Frame004 = new CATDlgFrame(this, "Frame004", CATDlgFraNoFrame|CATDlgGridLayout);
_Frame004 -> SetGridConstraints(1, 0, 1, 1, CATGRID_4SIDES);
 _PushButtonReadXml = new CATDlgPushButton(_Frame004, "PushButtonReadXml");
_PushButtonReadXml -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
 _Container007 = new CATDlgContainer(_Frame004, "Container007");
 _Container007 -> SetRectDimensions(1, 1, 5, 20);
_Container007 -> SetGridConstraints(0, 1, 1, 1, CATGRID_4SIDES);
 _PushButtonWriteXml = new CATDlgPushButton(_Frame004, "PushButtonWriteXml");
_PushButtonWriteXml -> SetGridConstraints(0, 2, 1, 1, CATGRID_4SIDES);
 _Container009 = new CATDlgContainer(_Frame004, "Container009");
 _Container009 -> SetRectDimensions(1, 1, 5, 5);
_Container009 -> SetGridConstraints(0, 3, 1, 1, CATGRID_4SIDES);
 _Frame011 = new CATDlgFrame(this, "Frame011", CATDlgGridLayout);
_Frame011 -> SetGridConstraints(2, 0, 1, 1, CATGRID_4SIDES);
 _SelectorListReadXml = new CATDlgSelectorList(_Frame011, "SelectorListReadXml");
 _SelectorListReadXml -> SetVisibleTextWidth(35);
_SelectorListReadXml -> SetGridConstraints(0, 0, 1, 1, CATGRID_4SIDES);
//END CAA2 WIZARD WIDGET CONSTRUCTION SECTION

//CAA2 WIZARD CALLBACK DECLARATION SECTION
//END CAA2 WIZARD CALLBACK DECLARATION SECTION

}

CATDlgPushButton* ReadXmlDlg::GetPushButtonReadXml()
{
	return _PushButtonReadXml;
}

CATDlgSelectorList* ReadXmlDlg::GetSelectorListShowXml()
{
	return _SelectorListReadXml;
}

CATDlgEditor* ReadXmlDlg::GetEditorSavePath()
{
	return _EditorSavePath;
}

CATDlgPushButton* ReadXmlDlg::GetPushButtonSelectPath()
{
	return _PushButtonSelectPath;
}

CATDlgPushButton* ReadXmlDlg::GetPushButtonWriteXml()
{
	return _PushButtonWriteXml;
}