//===================================================================
// COPYRIGHT tang 2022/05/05
//===================================================================
// AdoConn.cpp
// Header definition of class AdoConn
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2022/05/05 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef AdoConn_H
#define AdoConn_H

#include "TestAdoM.h"
#include "CATBaseUnknown.h"

#include <stdio.h>
#include <iostream>
#include <string.h>
#include <vector>
#include <sstream>
//#include "afxdb.h"
#import "C:\\Program Files\\Common Files\\System\\ado\\msado15.dll" no_namespace rename("EOF","adoEOF"),rename("BOF","adoBOF")  

using namespace std;

//-----------------------------------------------------------------------

class ExportedByTestAdoM AdoConn: public CATBaseUnknown
{
public:
// Standard constructors and destructors
// -------------------------------------
AdoConn ();
virtual ~AdoConn ();

//
// TODO: Add your methods for this class here.
//
HRESULT InitAdoConn();
void CloseAdoConn();
int ExecuteSQL(_bstr_t bstrSQL);
int SelectData(const string& sql,std::vector<string>& results);

private:
// Copy constructor and equal operator
// -----------------------------------
AdoConn (AdoConn &);
AdoConn& operator=(AdoConn&);
bool Connect();
bool ReConnect();

private:

	//定义变量  
	_ConnectionPtr		m_pConnection; //连接智能指针  
	_RecordsetPtr		m_pRecordset;//记录集智能指针  
	_CommandPtr			m_pCommand;  

};

//-----------------------------------------------------------------------

#endif
