// COPYRIGHT Dassault Systemes 2019
//===================================================================
//
// RPSInsertCmd.h
// The state chart based command: RPSInsertCmd
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   STATECOMMAND
//End CAA2 Wizard Generation Report
//
//  Jan 2019  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#ifndef RPSInsertCmd_H
#define RPSInsertCmd_H

#include "CATStateCommand.h"
#include "CATBoolean.h"

#include "RPSInsertDlg.h"

#include "CATIProduct.h"
#include "CATIMechanicalRootFactory.h"
#include "iostream.h"

#include "CATFrmEditor.h"
#include "CATDocument.h"
#include "CATIDocRoots.h"
#include "CATLISTV_CATBaseUnknown.h"
#include "CATIProduct.h"
#include "CATIDocId.h"

#include "CATIContainerOfDocument.h"
#include "CATIPrtContainer.h"
#include "CATIPrtPart.h"
#include "CATIPartRequest.h"
#include "CATIGSMFactory.h"
#include "CATIGSMPoint.h"
#include "CATIGSMProceduralView.h"
#include "CATIAlias.h"
#include "CATISpecObject.h"

#include "CATFrmEditor.h"
#include "CATDocument.h"
#include "CATIDocRoots.h"
#include "CATLISTV_CATBaseUnknown.h"
#include "CATFeatureImportAgent.h"
#include "CATDialogAgent.h"
#include "CATHSO.h"

#include "CATGetEnvValue.h"

#include "ClsOfExcelOperation.h"



class CATIndicationAgent;

//----------------------------------------------------------------------

/**
 * Describe your command here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog engine framework.
 * (consult base class description).
 */
class RPSInsertCmd: public CATStateCommand
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( RPSInsertCmd, CATStateCommand )

  public:

  RPSInsertCmd();
  virtual ~RPSInsertCmd();

    /**
     * Defines the command automata.
     * <br>
     * <i>(states, transitions and agents)</i>
     */
  virtual void     BuildGraph();

    /**
     * Action associated to state transitions.
     */
  virtual CATBoolean  ActionOne(void * data);

  void ExitCmd(void * data);

  void ActionInsert(void * data);

  HRESULT InsertRPS(CATIProduct_var ispProductTarget, CATUnicodeString istrGSName, CATUnicodeString istrRPSName, CATUnicodeString istrXCoord, CATUnicodeString istrYCoord, CATUnicodeString istrZCoord);
  HRESULT GetRootProduct(CATIProduct *&opiRootProduct);
  void SelectPart(void * data);
  void SelectTransfer(CATFeatureImportAgent *pFeatAgent,CATIProduct_var &ospProductSelect);
  void SetHighlight(CATFeatureImportAgent *ipFeatImpAgt);
  CATBoolean IsCATPart(CATFeatureImportAgent *ipFeatImpAgt);
  void ActionQuery(void * data);
  HRESULT GetResourseFile(CATUnicodeString &CATEnvPath,CATUnicodeString FileFullName,CATUnicodeString folderName);
  HRESULT GetQueryResult(CATUnicodeString istrFilePath, CATUnicodeString istrQueryWord, CATListValCATUnicodeString &olstQueryResult);
private:

  CATIndicationAgent	* _Indication;

  RPSInsertDlg * _pDlg;

  CATFeatureImportAgent * _pFeaImpAgt;

  CATDialogAgent * _pDlgAgt;

  //CATISpecObject_var _spSpecSelection;

  CATFrmEditor * _pEditor;

  CATHSO * _pHSO;

  CATIProduct_var _spProductSelect;

  CATUnicodeString _strDBPath;

};

//----------------------------------------------------------------------

#endif
