// COPYRIGHT Dassault Systemes 2020
//===================================================================
//
// SelectTreeItemNotif.h
// Header definition of SelectTreeItemNotif
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//
//  Apr 2020  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#ifndef SelectTreeItemNotif_H
#define SelectTreeItemNotif_H

#include "CATNotification.h"

//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* Do not use the @href SelectTreeItemNotif constructor to
* do such and such but instead...
*
* @example
*  // example is optional
*  pObject = new SelectTreeItemNotif;
*  pObject->SetXXX(...);
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class SelectTreeItemNotif: public CATNotification
{
  CATDeclareClass;

  public:

  // Standard constructors and destructors
  // -------------------------------------
     SelectTreeItemNotif ();
     virtual ~SelectTreeItemNotif ();

  // Copy constructor and equal operator
  // -----------------------------------
  SelectTreeItemNotif (SelectTreeItemNotif &);
  SelectTreeItemNotif& operator=(SelectTreeItemNotif&);

};

//-----------------------------------------------------------------------

#endif
