// COPYRIGHT Dassault Systemes 2020
//===================================================================
//
// TstEPointEdit.cpp
// Provide implementation to interface
//    CATIEdit
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Apr 2020  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#include "TstEPointEdit.h"
 
CATImplementClass(TstEPointEdit,
                  DataExtension,
                  CATExtIEdit,
                  TestExtendPt );
 

//-----------------------------------------------------------------------------
// TstEPointEdit : constructor
//-----------------------------------------------------------------------------
TstEPointEdit::TstEPointEdit():
    CATExtIEdit()
{
}

//-----------------------------------------------------------------------------
// TstEPointEdit : destructor
//-----------------------------------------------------------------------------
TstEPointEdit::~TstEPointEdit()
{
}
 
// Link the implementation to its interface
// ---------------------------------------



//TIE or TIEchain definitions
#include "TIE_CATIEdit.h"
TIE_CATIEdit( TstEPointEdit);


//Methods implementation

//-----------------------------------------------------------------------------
// Implements CATIEdit::Activate
//-----------------------------------------------------------------------------
CATCommand * TstEPointEdit::Activate (CATPathElement *  iPath)
{

   return NULL;
}

//-----------------------------------------------------------------------------
// Implements CATIEdit::GetInPanelEditor
//-----------------------------------------------------------------------------
CATDlgFrame * TstEPointEdit::GetInPanelEditor ()
{

   return NULL;
}

//-----------------------------------------------------------------------------
// Implements CATIEdit::GetPanelItem
//-----------------------------------------------------------------------------
CATDlgFrame * TstEPointEdit::GetPanelItem (CATDialog *  iParent , const CATString &  iTitle)
{

   return NULL;
}

