# COPYRIGHT Dassault Systemes 2019
#======================================================================
# Imakefile for module TrainingViewFeedbackM.m
#======================================================================
#
#  Jul 2019  Creation: Code generated by the CAA wizard  lxh
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0GROUP
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES) CATMathematics \
CATViz \
CATVisualization \
CATApplicationFrame \
JS0FM JS0GROUP \
CATViz  \
JS0CORBA \
SystemUUID \
CATObjectModelerBase \
# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
