// COPYRIGHT Dassault Systemes 2019
//===================================================================
//
// IdentityCard.h
// Supplies the list of prerequisite components for framework YFAirventXMLFrm
//
//===================================================================
//
// Usage notes:
//   For every prereq framework FW, use the syntax:
//   AddPrereqComponent ("FW", Public);
//
//===================================================================
//
//  Jul 2019  Creation: Code generated by the CAA wizard  lxh
//===================================================================
// DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
AddPrereqComponent ("System", Public);
// END WIZARD EDITION ZONE
