// COPYRIGHT Dassault Systemes 2019
//===================================================================
//
// TestUserDefinedMathBoxCmd.h
// The state chart based command: TestUserDefinedMathBoxCmd
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   STATECOMMAND
//End CAA2 Wizard Generation Report
//
//  Aug 2019  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#ifndef TestUserDefinedMathBoxCmd_H
#define TestUserDefinedMathBoxCmd_H

#include "CATStateCommand.h"
#include "CATBoolean.h"
#include "GeneralClass.h"
#include "CAACommonModule.h"

class CATIndicationAgent;

//----------------------------------------------------------------------

/**
 * Describe your command here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog engine framework.
 * (consult base class description).
 */
class TestUserDefinedMathBoxCmd: public CATStateCommand
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( TestUserDefinedMathBoxCmd, CATStateCommand )

  public:

  TestUserDefinedMathBoxCmd();
  virtual ~TestUserDefinedMathBoxCmd();

    /**
     * Defines the command automata.
     * <br>
     * <i>(states, transitions and agents)</i>
     */
  virtual void     BuildGraph();

    /**
     * Action associated to state transitions.
     */
  virtual CATBoolean  ActionOne(void * data);

  void GetPlaneFromScreen();
  CATBoolean AddHSO(CATBaseUnknown_var ispSpecSelect);
  private:

  CATIndicationAgent	* _Indication;

  GeneralClass			* _pGeneralCls;
};

//----------------------------------------------------------------------

#endif
