// COPYRIGHT Dassault Systemes 2018
//===================================================================
//
// MyAddinMain.h
// Provide implementation to interface
//    CATIAfrGeneralWksAddin
//    CATIWorkbenchAddin

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//IMPLEMENTATION
//    TIE: CATIAfrGeneralWksAddin
//    TIE: CATIWorkbenchAddin

//End CAA2 Wizard Generation Report
//
//  Nov 2018  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#ifndef MyAddinMain_H
#define MyAddinMain_H

#include "CATBaseUnknown.h"
#include "CATCmdContainer.h"
#include "CATCreateWorkshop.h"


//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href CATIAfrGeneralWksAddin
*  <li>@href CATIWorkbenchAddin
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class MyAddinMain: public CATBaseUnknown

{
  CATDeclareClass;

  public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
     MyAddinMain ();
     virtual ~MyAddinMain ();

     /**
     * Implements a function from an interface.
     * @href CATIWorkbenchAddin#CreateCommands
     */
     void CreateCommands () ;

     /**
     * Implements a function from an interface.
     * @href CATIWorkbenchAddin#CreateToolbars
     */
     CATCmdContainer * CreateToolbars () ;


  private:
  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  MyAddinMain (MyAddinMain &);
  MyAddinMain& operator=(MyAddinMain&);

};

//-----------------------------------------------------------------------

#endif
