// COPYRIGHT Dassault Systemes 2020
//===================================================================
//
// TstEBuild.h
// Provide implementation to interface
//    CATIBuild

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//EXTENSION:	TestExtendPt
//EXTENSIONTYPE:	DataExtension

//    TIE: CATIBuild

//End CAA2 Wizard Generation Report
//
//  Apr 2020  Creation: Code generated by the CAA wizard  Administrator
//===================================================================
#ifndef TstEBuild_H
#define TstEBuild_H

#include "CATBaseUnknown.h"

#include "TstIPoint.h"

// GeometricObjects Framework
#include "CATLine.h"                   // To query a direction
#include "CATCGMJournalList.h"

// MechanicalModeler Framework
#include "CATIMfProcReport.h"          // To manage the procedural report
#include "CATMfBRepDefs.h"             // Useful for the procedural report 
#include "CATMfErrUpdate.h"            // To manage mechanical modeler update error
#include "CATIUpdateError.h"           // To associate an error to a feature

// MecModInterfaces Framework
#include "CATIContainerOfDocument.h"   // To retrieve the geometrical factory
#include "CATIMechanicalProperties.h"   // 
#include "CATIDatumFactory.h"
#include "CATGeoFactory.h"    
#include "CATIMfResultManagement.h"
#include "CATIPrtContainer.h"

// ObjectModelerBase Framework
#include "CATLISTV_CATBaseUnknown.h"   // To store the CATBody of the input elements to follow
#include "CATILinkableObject.h"        // To retrieve the result container
#include "CATDocument.h"               // To retrieve the result container
#include "CATIContainer.h"
#include "CATInit.h"

// ObjectSpecsModeler Framework
#include "CATISpecObject.h"            // To query the Combined Curve feature about its inputs

// NewTopologicalObjects Framework
#include "CATBody.h"                   // The Topological result
#include "CATTopData.h"                // Needed to create operators

// System Framework
#include "CATListOfCATUnicodeString.h" // For the list of keys 
#include "CATUnicodeString.h"
#include "CATError.h"
#include "CATBoolean.h"

// TopologicalOperators Framework
#include "CATTopPointOperator.h"

// Mathematics Framework
#include "CATSoftwareConfiguration.h"  // Needed to create topological data

//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href CATIBuild
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class TstEBuild: public CATBaseUnknown

{
  CATDeclareClass;

  public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
     TstEBuild ();
     virtual ~TstEBuild ();

    /**
     * Implements a function from an interface.
     * @href CATIBuild#Build
     */
     HRESULT Build () ;

	 CATGeoFactory *GetGeoFactory();
	 CATIDatumFactory *GetDatumFactory();


  private:
  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  TstEBuild (TstEBuild &);
  TstEBuild& operator=(TstEBuild&);

};

//-----------------------------------------------------------------------

#endif
